version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-qrdb}
      POSTGRES_USER: ${POSTGRES_USER:-qruser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qrpass}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://qruser:qrpass@db:5432/qrdb}
      SECRET_KEY: ${SECRET_KEY:-dev-key}
      DEBUG: ${DEBUG:-false}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-http://localhost:8000}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1}
      DJANGO_COLLECTSTATIC: ${DJANGO_COLLECTSTATIC:-0}
      MIGRATE_ON_START: ${MIGRATE_ON_START:-1}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY:-3}
    ports:
      - "8000:8000"

volumes:
  pgdata:
