# Generated by Django 5.2.6 on 2025-09-25 01:32

import django.db.models.deletion
import qrapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('slug', models.SlugField(default=qrapp.models.default_slug, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('target_url', models.URLField(help_text='Destino actual del QR')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ua', models.TextField(blank=True, default='')),
                ('ref', models.TextField(blank=True, default='')),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='qrapp.qrcode')),
            ],
        ),
    ]
